# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c752822f3214ada99c2da21dcc46f32b4e53a846fecf191fefb9296b9e28cfe999e6f0c3adf30e4688147ec6c04ded112ee96c573cf144c67aaf6849be6c61c8

test:
  secret_key_base: 81608c37e58154b4502b6379442a55fb66fc4b224ee3410445e805867889fc716c416f65b8b7a9556b3a3ad9375f76b7de5d98cb1dd9651112b33cc7c3fd6ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
